name: "Main Branch Prebuild"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Updated to a newer Python version

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download NLTK Data
        run: |
          python -m nltk.downloader punkt vader_lexicon  # Specify only necessary NLTK data packages